codestates-seb/seb40_main_024

server/build.gradle
server/src/main/java/com/codestates/server/board/assembler/BoardAssembler.java
server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/dto/BoardDto.java
server/src/main/java/com/codestates/server/board/entity/Board.java
server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
server/src/main/java/com/codestates/server/board/service/BoardService.java
server/src/main/java/com/codestates/server/board/stub/BoardStub.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java
server/src/main/resources/application.yml

변경 사항:
- Spring security 주석 처리 되어있습니다. 사용시 확인 부탁드려요.
- h2 경로 변경하였습니다. -> jdbc:h2:mem:hojuMoney
- 이 외 gradle, .yml 변경 사항은 없습니다.

[be] feat: 게시판 기능 구현 중 외 h2 경로 변경

---

server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/dto/BoardDto.java
server/src/main/java/com/codestates/server/board/entity/Board.java
server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
server/src/main/java/com/codestates/server/board/stub/BoardStub.java

게시판 기본 구현 완료 하였습니다.
- 하나의 게시글 작성 POST
- 하나의 게시글 수정 PATCH
- 하나의 게시글 GET
- 전체 게시글 GET
- 하나의 게시글 DELETE

[BE] feat: 게시판 기본 기능 구현

---

README.md

변경 사항:
- 코드 컨벤션과 멤버 업데이트 하였습니다.

[BE] docs: 기본 리드미 업데이트

---

server/.gitignore
server/src/main/java/com/codestates/server/board/entity/Board.java

[BE] fix: .gitignore upddate

---

server/src/main/java/com/codestates/server/audit/Auditable.java
server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/dto/BoardDto.java
server/src/main/java/com/codestates/server/board/entity/Board.java
server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
server/src/main/java/com/codestates/server/board/service/BoardService.java
server/src/main/java/com/codestates/server/board/stub/BoardStub.java
server/src/main/java/com/codestates/server/comment/assembler/CommentAssembler.java
server/src/main/java/com/codestates/server/comment/controller/CommentController.java
server/src/main/java/com/codestates/server/comment/dto/CommentDto.java
server/src/main/java/com/codestates/server/comment/entity/Comment.java
server/src/main/java/com/codestates/server/comment/mapper/CommentMapper.java
server/src/main/java/com/codestates/server/comment/repository/CommentRepository.java
server/src/main/java/com/codestates/server/comment/service/CommentService.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java

- 댓글 CRUD 구현 완료 
- 게시판과 매핑 완료
- Comment API 명세서 업데이트 완료 (https://www.notion.so/codestates/API-9e1a3f68ddd5408b90c3ac5301e7c0de)
- #31

[BE] feat: 댓글 구현 완료 (+ 게시판과 매핑)

---

server/src/main/generated/com/codestates/server/asset/mapper/AssetMapperImpl.java
server/src/main/generated/com/codestates/server/board/mapper/BoardMapperImpl.java
server/src/main/generated/com/codestates/server/comment/mapper/CommentMapperImpl.java
server/src/main/java/com/codestates/server/asset/controller/AssetController.java
server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
server/src/main/java/com/codestates/server/asset/entity/Asset.java
server/src/main/java/com/codestates/server/asset/mapper/AssetMapper.java
server/src/main/java/com/codestates/server/asset/repository/AssetRepository.java
server/src/main/java/com/codestates/server/asset/service/AssetService.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java

assetValue : string -> long 타입으로 바꿨습니다
post, get, delete는 확인 완료
patch는 오류가 있어 다시 수정하겠습니다!
reflog 한 파일입니다

[BE] feat: asset crud 기본 구현

---

server/src/main/java/com/codestates/server/board/assembler/BoardAssembler.java
server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
server/src/main/java/com/codestates/server/board/service/BoardService.java
server/src/main/java/com/codestates/server/board/stub/BoardStub.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java
server/src/main/java/com/codestates/server/goal/assembler/GoalAssembler.java
server/src/main/java/com/codestates/server/goal/controller/GoalController.java
server/src/main/java/com/codestates/server/goal/dto/GoalDto.java
server/src/main/java/com/codestates/server/goal/entity/Goal.java
server/src/main/java/com/codestates/server/goal/mapper/GoalMapper.java
server/src/main/java/com/codestates/server/goal/repository/GoalRepository.java
server/src/main/java/com/codestates/server/goal/service/GoalService.java

- 게시판 page 기능 추가 하였습니다.
- 좋아요 기능 추가하였습니다. -> like 와 dislike 두 개의 엔드포인트를 갖고 있습니다.
- 목표 자산 기능 (옵션 1) 구현 완료 하였습니다.
#42

[BE] feat: 목표 자산 기능 구현, 게시판 좋아요 및 페이지 업데이트

---

server/src/main/java/com/codestates/server/asset/controller/AssetController.java
server/src/main/java/com/codestates/server/board/service/BoardService.java

문제 원인:
Patch 에서 아이디를 제대로 받아오지 못하고 있습니다.
해결:
매퍼를 통해 패치를 에셋으로 먼저 변경 후 셋 아이디를 해서 해결했습니다. 
컨트롤러 확인 부탁드립니다! 👍 
#53

[BE] fix: Asset patch 버그 수정

---

front/src/Component/Board/BoardList.js
front/src/Component/Common/Navbar.js
front/src/Component/Common/Sidebar.js
front/src/Component/Member/ForgotPasswordBox.js
front/src/Component/Member/LoginBox.js
front/src/Component/Member/SignupBox.js
front/src/Pages/Board/AssetBoardPage.js
front/src/Pages/Board/FreeBoardPage.js

Fe/lim 합치기

---

front/.eslintrc.json
front/src/App.js
front/src/Component/Asset/AssetSettingTest.js
front/src/Component/Asset/Asset_B_Data_test.js
front/src/Pages/Asset/AssetTargetPage.js
front/src/Pages/Asset/AssetTargetTest.js

feat: 그래프 데이타 수정

---

front/src/Pages/Asset/AssetTargetTest.js

"feat : nan, infinity 필터함"

---

server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
server/src/main/java/com/codestates/server/goal/controller/GoalController.java
server/src/main/java/com/codestates/server/goal/dto/GoalDto.java
server/src/main/java/com/codestates/server/goal/service/GoalService.java

변경 사항:
- 목표 자산 성취도 구현
- 게시판 like 관련 버그 수정

[BE] feat: 자산 관리 성취도 구현

---

server/src/main/java/com/codestates/server/stub/Stub.java

[BE] fix: stub 랜덤 댓글 수정

---

server/src/main/java/com/codestates/server/ServerApplication.java
server/src/main/java/com/codestates/server/configuration/WebConfig.java
server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java

변경 사항:
- web config 추가
- 주석부 확인 부탁드립니다.

[BE] feat: ngrok 통신을 위한 CORS 설정

---

server/src/main/java/com/codestates/server/stub/Stub.java

[BE] fix: Stub 랜덤 자산 X10 업데이트

---

front/.env
front/src/Component/Board/BoardContents.js
front/src/Component/Board/BoardFreeList.js
front/src/Pages/Board/BoardContentPage.js
front/src/index.js

feat: 게시글상세페이지 좋아요 css 추가

---

server/src/main/java/com/codestates/server/board/dto/BoardDto.java
server/src/main/java/com/codestates/server/board/entity/Board.java
server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
server/src/main/java/com/codestates/server/comment/dto/CommentDto.java
server/src/main/java/com/codestates/server/comment/entity/Comment.java
server/src/main/java/com/codestates/server/comment/mapper/CommentMapper.java
server/src/main/java/com/codestates/server/stub/Stub.java

변동사항: 
- 게시글 리스폰스에 멤버 데이터 추가
- 댓글 리스폰스에 멤버 데이터 추가
- stub 데이터 추가 -> 사용자 10명 생성 / 게시글(30개), 댓글(60개) 랜덤 배정

[BE] feat: stub 추가 / 게시글과 댓글 리스폰스에 작성자 정보 포함

---

server/src/main/java/com/codestates/server/board/dto/BoardDto.java
server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
server/src/main/java/com/codestates/server/comment/controller/CommentController.java
server/src/main/java/com/codestates/server/comment/dto/CommentDto.java
server/src/main/java/com/codestates/server/comment/mapper/CommentMapper.java
server/src/main/java/com/codestates/server/comment/service/CommentService.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java

변경사항:
- 댓글 URI 변경 (`board/{board_id}/comment/{comment_id}`)
- 변경에 따른 보드 검증 로직 추가
- 게시글과 댓글의 멤버 리스폰스 필요한 정보만 주도록 수정

[BE] feat: 댓글 URI 변경 / 보드 검증 로직 추가 / 게시글, 댓글 리스폰스 수정

---

server/build.gradle
server/src/main/java/com/codestates/server/board/dto/BoardDto.java
server/src/main/java/com/codestates/server/board/entity/Board.java
server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
server/src/main/java/com/codestates/server/board/service/BoardService.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java
server/src/main/java/com/codestates/server/stub/Stub.java

변동사항:
- 게시판 태그 추가 (일반, 자산) - java enum type
- 태그 관련 exception 추가
- 게시판 mapper 리팩터링
- stub 게시글 랜덤 태그 배정

[BE] feat: 게시판 태그 추가 / exception 추가 / stub 랜덤 태그 배정

---

server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
server/src/main/java/com/codestates/server/board/service/BoardService.java

변경사항:
- 컨틑롤러 페이지 관련 리팩터링
- 태그별로 모아보기 추가 (일반태그, 자산태그 page 모아보기)
- PATCH 시 게시물 tag 옵셔널로 수정

[BE] feat: 게시글 태그별로 모아보기 / PATCH 시 게시글 tag 옵셔널로 변경

---

server/src/main/java/com/codestates/server/stub/Stub.java

현재 stub 멤버 (10)명 자산 쪽에 랜덤 배정 되도록 하였습니다.

[BE] feat: asset stub - 멤버 랜덤 배정

---

server/src/main/java/com/codestates/server/board/assembler/BoardAssembler.java
server/src/main/java/com/codestates/server/board/entity/Board.java
server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
server/src/main/java/com/codestates/server/goal/entity/Goal.java
server/src/main/java/com/codestates/server/stub/Stub.java

변경사항:
- board status (Enumerated type ORDINAL -> STRING)
- 게시글 links href 수정
- stub 목표자산 랜덤 15 추가

[BE] refactor: board status (ordinal -> string), link href fix / Goal 랜덤 자산 15개 stub 추가

---

server/src/main/java/com/codestates/server/goal/dto/GoalDto.java
server/src/main/java/com/codestates/server/goal/entity/Goal.java
server/src/main/java/com/codestates/server/goal/mapper/GoalMapper.java
server/src/main/java/com/codestates/server/goal/service/GoalService.java
server/src/main/java/com/codestates/server/stub/Stub.java

변경사항:
- 목표 자산 response 멤버 정보 추가
- 목표 자산 PATCH -> 가격 이외 항목들 옵셔널로 로직 변경
- 목표 기간 검증 로직 추가 (Arithmetic exception 방지)

[BE] feat: 목표 자산 PATCH 로직 변경 / targetLength 검증

---

server/src/main/java/com/codestates/server/board/entity/Board.java
server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java
server/src/main/java/com/codestates/server/goal/controller/GoalController.java
server/src/main/java/com/codestates/server/goal/dto/GoalDto.java
server/src/main/java/com/codestates/server/goal/entity/Goal.java
server/src/main/java/com/codestates/server/goal/repository/GoalRepository.java
server/src/main/java/com/codestates/server/goal/service/GoalService.java

변경사항:
- 목표자산 멤버별 조회로 수정 
- 엔드포인트 변경 (api 문서 참조 부탁드립니다.. 🙇)
- 성취도 관련 중복코드 제거

[BE] feat: GOAL -> 멤버별 조회 추가, 엔드포인트 변경, 중복코드 제거

---

.idea/.gitignore
.idea/compiler.xml
.idea/gradle.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/modules.xml
.idea/seb40_main_024.iml
.idea/vcs.xml
server/src/main/java/com/codestates/server/asset/controller/AssetController.java
server/src/main/java/com/codestates/server/asset/dto/AssetDto.java
server/src/main/java/com/codestates/server/asset/entity/Asset.java
server/src/main/java/com/codestates/server/asset/mapper/AssetMapper.java
server/src/main/java/com/codestates/server/asset/repository/AssetRepository.java
server/src/main/java/com/codestates/server/asset/service/AssetService.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java

post 할 때 member Id 값은 아직 null로 들어와서 확인 후 수정하겠습니다

[BE] feat: assetType 명칭 수정 & member Id 값 추가

---

front/src/Component/Common/Modal.js
front/src/Pages/Asset/AssetChange.js
front/src/Pages/Asset/AssetChangeTest.js

- 자산페이지 전체 CSS 수정
- 모달창 구현
- ACCESS TOKEN, REFRESH TOKEN 틀만 구성함(BE 재발급요청 루트 대기중) ->TEST 전

[dev] FE 머지

---

server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
server/src/main/java/com/codestates/server/board/service/BoardService.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java

변경사항:
- like 관련 예외처리
- Board controller 간소화, 예외처리 등

[BE] fix: Board controller 간소화, like 예외처리 등

---

server/build.gradle
server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/service/BoardService.java

변경사항:
- 게시판 불필요 로직 제거
- gradle 현재 안쓰는 디펜던시 및 플러그인 주석처리

[BE] refactor: 게시판 불필요 로직 제거 외

---

server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/dto/BoardDto.java
server/src/main/java/com/codestates/server/board/entity/Board.java
server/src/main/java/com/codestates/server/board/mapper/BoardMapper.java
server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
server/src/main/java/com/codestates/server/board/service/BoardService.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java
server/src/main/java/com/codestates/server/stub/Stub.java

변경사항:
- 게시판 리스폰스 tag -> category 🙇

[BE] fix: tag renaming -> Category

---

server/src/main/java/com/codestates/server/board/repository/BoardRepository.java
server/src/main/java/com/codestates/server/goal/entity/Goal.java
server/src/main/java/com/codestates/server/goal/service/GoalService.java

변동사항:
- 페이지 조회시 desc 순서로 수정
- 목표자산 calculated price 올림 되도록 수정
(바로 재배포 하도록 하겠습니다... )

[BE] fix: 쿼리 order by 수정 / ceiling 으로 수정

---

server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/dto/BoardDto.java
server/src/main/java/com/codestates/server/board/service/BoardService.java
server/src/main/java/com/codestates/server/comment/controller/CommentController.java
server/src/main/java/com/codestates/server/comment/dto/CommentDto.java
server/src/main/java/com/codestates/server/comment/service/CommentService.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java
server/src/main/java/com/codestates/server/member/service/MemberService.java

[BE] fix: 리버트의 리버트..

---

server/src/main/java/com/codestates/server/board/controller/BoardController.java
server/src/main/java/com/codestates/server/board/service/BoardService.java
server/src/main/java/com/codestates/server/comment/controller/CommentController.java
server/src/main/java/com/codestates/server/comment/service/CommentService.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java

변경사항:
- 게시판 -> 로그인 사용자 관련 예외처리 
- 게시판 -> POST 외 UPDATE, DELETE 로그인 사용자 확인 추가
- 댓글 -> POST, UPDATE, DELETE 로그인 사용자 확인 / 예외처리 추가

[BE] feat: Board & Comment -> POST, UPDATE, DELETE 로그인 사용자

---

server/src/main/java/com/codestates/server/board/dto/BoardDto.java
server/src/main/java/com/codestates/server/comment/dto/CommentDto.java
server/src/main/java/com/codestates/server/exception/ExceptionCode.java
server/src/main/java/com/codestates/server/goal/assembler/GoalAssembler.java
server/src/main/java/com/codestates/server/goal/controller/GoalController.java
server/src/main/java/com/codestates/server/goal/service/GoalService.java

변경사항:
- GET, POST, PATCH, DELETE 등 전체 관련 메서드에 로그인 사용자 적용 및 관련 예외처리
- URL 더 restful  하도록 변경 (노션 참고해 주세요..)
https://www.notion.so/codestates/API-9e1a3f68ddd5408b90c3ac5301e7c0de#4a7491e149f04f3ab49b87c8a60f8f7b

[BE] feat: Goal -> 로그인된 사용자 확인 적용

---

server/src/main/java/com/codestates/server/goal/service/GoalService.java

[BE] fix: 목표자산 PATCH 관련

---

server/src/main/java/com/codestates/server/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/codestates/server/config/SecurityConfiguration.java
server/src/main/java/com/codestates/server/member/service/MemberService.java

redis, oauth2 아직 구현 중이신 것 같은데 yml, 환경변수, 그레이들 다 제대로 준비 안돼있어서 일단 편집 합니다. 
나중에 구현 다 하시면 확인 후 머지 부탁 드립니다.

[BE] fix: 성학님 커밋 이후 빌드실패 픽스

---

server/src/main/java/com/codestates/server/config/SecurityConfiguration.java

[BE] origin 설정

---

front/src/Pages/Asset/AssetChange.js

feat: 제출 전 업로드!

---

front/src/App.js
front/src/Component/Common/Button.js
front/src/Component/Common/Modal.js
front/src/Pages/Asset/AssetChange.js

feat: 자산페이지
